### PR TITLE
Fix Error getting Wi-Fi connections

### LINKED ISSUE #7: Error getting Wi-Fi connections
Hey again,

Running `wifi-share.py --list` fails, but I have a lot of wireless connections saved:
```sh
~proj/misc/wifi-share (git)-[master] % ./wifi-share.py --list
[-] Error getting Wi-Fi connections
~proj/misc/wifi-share (git)-[master] % nmcli connection show |& grep --color=auto wireless | wc -l
153
```

I think I found the problem. I will provide a PR in a few minutes.

### PR DESCRIPTION
**Pull request by jkirk**
Displaying the list of stored Wi-Fi networks (SSIDs) to choose from
failed. The problem on this side is that the type of the Wi-Fi network
connections is '802-11-wireless' which does not contain 'wifi'.

To be backward compatible we search for "wireless" and "wifi".

Then the second problem is that it was assumed that the network
connection does not contain white spaces. To overcome that limitation
we changed to the "terse" output format which makes it easier to grep
for the connection name (the fields are delimited with ":").

And finally "nmcli connection show" does not show SSIDs but "connection
names", so we have to retrieve the wifi_name from the connection_name.

Closes: thanosgn/wifi-share#7

### CODE REVIEW

**Comment by thanosgn** [comment]
Hi, can you please post the output of `wifi-share -l` after the changes?

In my case the `connection_names` and SSIDs were identical.

**Comment by jkirk** [comment]
Hey, 

the output of `wifi-share -l` looks something like this:

```
~proj/misc/wifi-share (git)-[fix-list-networks] % ./wifi-share.py -l
? Wi-Fi connection:  (Use arrow keys)
 ❯ Auto #AirportExample
   Auto 30 Min. Free Wi-Fi - Example
   Auto 3Example
   Auto 7Links-RepeaterExample
[...]
```

As already mentioned in #4, most of the `connection_names` are in the format of `Auto $SSID`

**Comment by thanosgn** [comment]
Hello again,

I have a few notes.

- I strongly believe that the list should be populated by SSIDs rather than connection names. For example some people may find `Auto 7Links-RepeaterExample` meaningless and would want to see ` 7Links-Repeater`. Also, since we don't know the connection name format of all OS / NetworkManager configurations we cannot guarantee that the connection name will be descriptive enough to understand the corresponding SSID.

- `--terse` argument for `nmcli` displays `802-11-wireless` instead of `wifi`. Without the `--terse` argument the type field is `wifi`. That's why we should search for  `802-11-wireless` should we decide to use `--terse`. You were right about the whitespace mistake.

- I have written a revised version generating the wifi list for the `--list` execution (together with other chagnes). The list displays SSIDs, and the user chooses an SSID from the dropdown menu, which is the intuitive thing to do. Along with the SSID we also keep the connection name. In my opinion this is currently the most suitable (though not the most efficient, due to multiple invocations of `nmcli`) solution.

Issue #7 should be closed now.

Thanks again for the feedback. 
Cheers!

**Comment by jkirk** [comment]
Hey,

- SSID vs connection names: YES. I also think listing SSDs would be much better!
- `--terse`: ok
- Update: Nice. I will test it and will let you know it solves the issue for me too.

Thank you!

**Comment by jkirk** [comment]
Just tested the updated version. And it works.. But: with 166 connections it takes about 26(!) seconds to get the list of SSIDs. (I initially thought the program stuck.) I am sorry to say that, but this is nearly unusable (for me).

If you find a solution for this problem, I would really appreciate it. Thx!

**Comment by thanosgn** [comment]
I am aware of the performance issue when using the `--list` option.

I will try to find a more efficient way of doing this. 

Any suggestion is welcome though.

Cheers!

**Pull request closed without merging**
