### PR TITLE
Fix Error getting Wi-Fi password

### LINKED ISSUE #4: Error getting Wi-Fi password
Hi,

Running `wifi-share` (via sudo) returns:
```
[-] Error getting Wi-Fi password
```

After a little bit of debugging it turned out that NetworkManager on my system (Debian/stretch with network-manager 1.6.2-3+deb9u2) saves the connections in the file `Auto $ESSID` which causes the line of subject to fail:
https://github.com/thanosgn/wifi-share/blob/15488ec95e8747728f64ac4106a6541dc694720d/wifi-share.py#L173

My workaround looks like this:
```
% git diff
diff --git a/wifi-share.py b/wifi-share.py
index 7445e64..366326a 100755
--- a/wifi-share.py
+++ b/wifi-share.py
@@ -170,7 +170,7 @@ def main():
                 if wifi_name == None:
                     raise ProcessError
             else:
-                with open( os.path.join('/etc/NetworkManager/system-connections', wifi_name), 'r') as network_file:
+                with open( os.path.join('/etc/NetworkManager/system-connections', 'Auto ' + wifi_name), 'r') as network_file:
                     for line in network_file:
                         if 'psk=' in line:
                             wifi_password = line.split('=')[1].rstrip('\r\n')
```

I wonder what the "best" fix would look like. The system connection file does not necessarily needs to be `wifi_name` or even `Auto wifi_name`. Maybe we should grep for the SSID in every file instead?

### PR DESCRIPTION
**Pull request by jkirk**
iwgetid(8) was used to find out the ESSID of the wireless network that is
currently used. Unfortunately iwgetid needs root / sudo rights, that's
why I replaced the code with nmcli.

nmcli uses connection IDs / name to identify the connection. One can not
assume that the connection name is the same as the wifi name so I
introduced a new variable `connection_name` to be used in nmcli to find
out the wifi password.

I am not sure how a connection without wifi-password looks like or
rather what nmcli retruns in that case. We need to test that case.

Closes: thanosgn/wifi-share#4

### CODE REVIEW

**Comment by thanosgn** [comment]
Hello,

Nice job, I was also about to replace `iwgetid` with an `nmcli` invocation. It is more consistent that way.

Please clarify something to me, did the replacement of `grep` command for the `802-11-wireless-security.psk` (line 210) solve the problem in your case?

**Comment by thanosgn** [comment]
To be more specific, with "problem" I do not mean the `sudo` requirement for `iwgetid`. I am referring to `wifi-share` reporting that your network (`home.example.com`) does not need a password.

**Comment by thanosgn** [comment]
Ok now looking back at this I noticed the `connection_name` in the last command.

As per your question: 

> I am not sure how a connection without wifi-password looks like or
rather what nmcli returns in that case. We need to test that case.

For networks without a password, the `802-11-wireless-security.psk` is not present so `nmcli` returns no output, and `wifi-share` knows that the network requires no password.

If you could verify that it works in your case now, I would be happy to merge this PR.

**Comment by jkirk** [comment]
> Please clarify something to me, did the replacement of `grep` command for the `802-11-wireless-security.psk` (line 210) solve the problem in your case?

You mean this change? https://github.com/thanosgn/wifi-share/blob/6e34f2d6926a748c34a602127ec0723e86479d9e/wifi-share.py#L210-L211

Actually the change of the position of the (global) option _--show-secrets_ did the trick (the replacement of `grep` was merely cosmetic):

```sh
% nmcli --terse --fields 802-11-wireless-security.psk --show-secrets connection show id "Auto home.example.com"
802-11-wireless-security.psk:THEWIFIPASSWORD
```
**vs**

```sh
% nmcli --terse --fields 802-11-wireless-security.psk connection show id "Auto home.example.com" --show-secrets
802-11-wireless-security.psk:<hidden>
Error: --show-secrets - no such connection profile.
```

And if _no password_ works you, perfect! :+1:

**Pull request merged**
